@startuml
hide footbox
autonumber
title Backstage new service flow

actor "Developer" as developer

participant "Backstage IDP" as idp

participant "Service" as service

actor "Platform" as platform
participant "ArgoCD repo" as argo
box "K8s cluster"
  participant "K8s Cluster:\nArgo Deployment" as argo_dep
  participant "K8s Cluster:\nTeam namespace" as namespace
end box

== Create Service in Backstage ==

group Create Service
  developer -> service: select service from the catalogue\nand fill the form
  service --> repository **: create
  service --> CI_pipeline **: trigger
  service --> argo: create PR to
end

== Deploy Service to Kubernetes cluster ==

group Approval
  platform -> argo: approves PR
  argo -> "Service App" **: creates
  group Service Deployment
    argo_dep -> namespace: deploy
  end
end

== Consume Service information via Backstage ==

developer -> idp: view and interact with the service

@enduml

